### ISSUE TITLE
Errors installing remnux as a addon

### ISSUE THREAD

**Issue by tompolth** [ekristen/cast#67]
Hi, 

I´ve just installed Sift using cast and it was successful. However when I try to install remnux using  (sudo cast install --mode=addon remnux/salt-states) I get many errors
Attached I include the log file generated during the install

[saltstack.log](https://github.com/ekristen/cast/files/12386705/saltstack.log)

I'd appreciate your help.
thanks

**Comment by ekristen** [comment]
This looks to be a bug in the remux saltstack states at first glance but I'd have to dig a bit deeper to know for sure. Unfortunately I don't have much time at the moment to do this, I can try and find some time in the coming week.

**Comment by digitalsleuth** [comment]
Hi @tompolth , can you tell me what version of Ubuntu you're attempting to install REMnux on? The initial error in the log you provided identifies an inability to map the `os_rel` variable. At this time, only Ubuntu Focal is supported for REMnux, with incoming support for Jammy. While the current state files do provide the "ability" to install on Bionic, the full installation of REMnux is not currently supported on this version.

Given that Python 3.8 is the default version on Ubuntu Focal, and 3.10 is Ubuntu Jammy, the issue is likely due to the OS version, because the first error in the log file you provided is:
```bash
[5376] WARNING: file already exists but should not: /tmp/_MEIVPhBnv/cryptography/hazmat/bindings/_openssl.abi3.so
[5376] WARNING: file already exists but should not: /tmp/_MEIVPhBnv/cryptography/hazmat/bindings/_padding.abi3.so
[5376] WARNING: file already exists but should not: /tmp/_MEIVPhBnv/immutables/_map.cpython-39-x86_64-linux-gnu.so
[5376] WARNING: file already exists but should not: /tmp/_MEIVPhBnv/markupsafe/_speedups.cpython-39-x86_64-linux-gnu.so
[5376] WARNING: file already exists but should not: /tmp/_MEIVPhBnv/msgpack/_cmsgpack.cpython-39-x86_64-linux-gnu.so
[5376] WARNING: file already exists but should not: /tmp/_MEIVPhBnv/psutil/_psutil_linux.cpython-39-x86_64-linux-gnu.so
[5376] WARNING: file already exists but should not: /tmp/_MEIVPhBnv/psutil/_psutil_posix.cpython-39-x86_64-linux-gnu.so
[5376] WARNING: file already exists but should not: /tmp/_MEIVPhBnv/yaml/_yaml.cpython-39-x86_64-linux-gnu.so
[5376] WARNING: file already exists but should not: /tmp/_MEIVPhBnv/zmq/backend/cython/_device.cpython-39-x86_64-linux-gnu.so
[5376] WARNING: file already exists but should not: /tmp/_MEIVPhBnv/zmq/backend/cython/_poll.cpython-39-x86_64-linux-gnu.so
[5376] WARNING: file already exists but should not: /tmp/_MEIVPhBnv/zmq/backend/cython/_proxy_steerable.cpython-39-x86_64-linux-gnu.so
[5376] WARNING: file already exists but should not: /tmp/_MEIVPhBnv/zmq/backend/cython/_version.cpython-39-x86_64-linux-gnu.so
[5376] WARNING: file already exists but should not: /tmp/_MEIVPhBnv/zmq/backend/cython/context.cpython-39-x86_64-linux-gnu.so
[5376] WARNING: file already exists but should not: /tmp/_MEIVPhBnv/zmq/backend/cython/error.cpython-39-x86_64-linux-gnu.so
[5376] WARNING: file already exists but should not: /tmp/_MEIVPhBnv/zmq/backend/cython/message.cpython-39-x86_64-linux-gnu.so
[5376] WARNING: file already exists but should not: /tmp/_MEIVPhBnv/zmq/backend/cython/socket.cpython-39-x86_64-linux-gnu.so
[5376] WARNING: file already exists but should not: /tmp/_MEIVPhBnv/zmq/backend/cython/utils.cpython-39-x86_64-linux-gnu.so
[5376] WARNING: file already exists but should not: /tmp/_MEIVPhBnv/zmq/devices/monitoredqueue.cpython-39-x86_64-linux-gnu.so
# [INFO    ] Loading fresh modules for state activity
# [ERROR   ] Rendering exception occurred
Traceback (most recent call last):
  File "salt/utils/templates.py", line 469, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 34, in top-level template code
jinja2.exceptions.UndefinedError: 'os_rel' is undefined
```
Since there are errors here related to cpython39, I want to make sure we determine the version you're running the installation on before we can provide a resolution. If this issue continues, please open an issue on the [REMnux Issues Page](https://github.com/REMnux/remnux-cli/issues/) so we can accurately track the issue there. Ultimately, based on the information you provided, this isn't actually a Cast issue.

**Comment by tompolth** [comment]
You're right. I have tried to install it in the Jammy version instead of Focal. I guess I'll have to repeat the process going back to 20.04. is it so?

**Comment by digitalsleuth** [comment]
Hi @tompolth , yes, for the time being Focal is the latest OS to be supported for REMnux. There are a few applications used in REMnux which do not yet support, or have not yet been built for Jammy, so we are working to get those applications up to date.

**Comment by tompolth** [comment]
Let's wait then. In the meantime I'll try it with Focal.

Many thanks
